import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from './Landing.module.scss'

const Home: NextPage = () => {

    return (
        <div className={styles.landing}>
            <div className={'container-fluid'}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className=''>
                    <div className={`row ${styles.header} pb-md-3`}>
                        <h1 className={styles.titleLogo}>Know<span>speak</span></h1>
                        <div className='col-12 col-md-7 '>
                            <h2 className={`${styles.title} mt-3 mt-md-5`}>Aprende ingles viendo videos</h2>
                            <div className={`${styles.containerImageHeader} d-md-none`}>
                                <img src='/assets/images/inicial.png' className={styles.verticalCellphoneHeader} />
                            </div>
                            <p className={`mt-2 mb-4 mt-md-3 ${styles.description}`}>Analiza palabra por palabra y frase por frase a través de los subtitulos</p>
                            <div className={`${styles.containerStoreImage} mb-3`}>
                                <img src='/assets/images/google-play-badge.png' className={`${styles.storeImage} mb-4`} />
                            </div>
                        </div>
                        <div className='col-12 col-md-5 d-none d-md-block'>
                            <div className={styles.containerImageHeader}>
                                <img src='/assets/images/inicial.png' className={styles.verticalCellphoneHeader} />
                            </div>
                        </div>
                    </div>
                    <div className={`${styles.whiteSection} justify-content-center row py-5`}>
                        <div className='col-12 col-md-8 col-lg-6'>
                            <img src='/assets/images/partes-del-traductor.png' className='img-fluid' />
                        </div>
                    </div>
                    <div className={`row mt-5 justify-content-center align-items-center`}>
                        <div className='col-12 col-md-5 col-lg-4 mb-3 order-md-2'>
                            <h3>1) Seleciona un video</h3>
                            <p>Accede a tu galería o agrega el link, puedes incluso ver video de Youtube, solo debes agregar el link que usas para compartir y colocarlo en el formulario.</p>
                        </div>
                        <div className='col-12 col-md-5 col-lg-3 d-flex justify-content-center order-md-1'>
                            <img src='/assets/images/border-in-field-video.png' className={styles.verticalCellphone} />
                        </div>
                    </div>

                    <div className={`${styles.whiteSection} align-items-center justify-content-center row mt-5 py-5`}>
                        <div className='col-12 col-md-5 col-lg-4 mb-3'>
                            <h3> 2) Agrega los subtitulos</h3>
                            <p>Puedes cargar un archivo .srt o .vtt que son donde por lo general se guardan los subtitlos de un video o también puedes agregar el link.</p>
                            <p>Nota: Para videos de youtube no es necesario buscar los subtitlos, ya estos vienen incluidos en el video</p>
                        </div>
                        <div className='col-12 col-md-5 col-lg-3 d-flex justify-content-center'>
                            <img src='/assets/images/border-in-field-to-subtitles.png' className={styles.verticalCellphone} />
                        </div>
                    </div>
                    <div className={`row mt-5 justify-content-center  align-items-center pb-5`}>
                        <div className='col-12 col-md-5 col-lg-4 mb-3 order-md-2'>
                            <h3>3) Disfruta viendo el video</h3>
                            <p>Una vez empiezes a ver el video los subtitlos apareceran, si no entiendes una palabra pudues precionar sobre ella y se abrirá una ventana donde la puedes analizar, viendo la traducción al español y escuchandola en distintas velocidades</p>
                            <p>Puesdes selecionar más de una palabra para analizar la frase completa.</p>
                        </div>
                        <div className='col-12 col-md-5 col-lg-6 order-md-1'>
                            <img src='/assets/images/inicial-video.png' className={'img-fluid'} />
                        </div>
                    </div>
                    <div className={`${styles.whiteSection} justify-content-center row pt-5 pb-5`}>
                        <div className='col-12 col-md-8 col-lg-6'>
                            <img src='/assets/images/player-buttons.png' className='img-fluid' />
                        </div>
                    </div>

                </main>

            </div >
            <footer className={`${styles.footer} `}>
                <a className={styles.link} href='#'>Políticas de privacidad</a>
            </footer>
        </div >
    )
}

export default Home
